# fly.toml app configuration file generated for my-mysql-app-winter-frog-1114 on 2024-08-14T10:22:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-mysql-app-winter-frog-1114'
primary_region = 'cdg'

[build]
  image = 'mysql'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
